= Ultimate Cookie

Ultimate Cookie is an automation suite for the Cookie Clicker game (http://orteil.dashnet.org/cookieclicker/). It is 
a work in progress for now while I add support for the current game version as it was neglected as a project since the
1.0466 version of the game.

The goal was to play the game as fast and as efficiently as possible while only acting in a manner that a human sitting at
the computer could theoretically do (assuming they could click the cookie hundreds of times a second). This primarily means
no working around the games internal clicks per second limit of 250 (in practice you won't really get this anyway).

What is working now and what is yet to do:
- Auto clicks, auto purchases, purchase prioritisation is working.
- Building prices and scaling are all up to date.
- 178 / 356 upgrades supported.

To load this mod in game bring up a javascript console and enter the command:

Game.LoadMod('https://rawgithub.com/eamonno/ultimatecookie/master/ultimatecookie.js')

Known issues:
- Purchasing stalls during most multiplier golden cookies (except for frenzy).
- No support for prestige.
- Not all upgrades are supported, there have been a huge number of changes to these over time so I am having to go back.
  and update them one by one. There are also a lot of new upgrades (150ish) that I need to add support for.
- Purchasing an unsupported upgrade disables purchases (this isn't a bug, its a config option, set Config.failHard to false to change it).
- Seasons not supported.
- The new frenzy types not supported (they dont do harm but they are not accounted for in calculations).

Time to unlock prestige 1 on new save:
- 04-Dec-2017 - 4 hours 17 mins.
- 08-Dec-2017 - 2 hours 14 mins.
