//
// TO-DO List
//
// Adjust for the AutoBuy delay in the autobuy function for very high reset regen rates
// Implement a proper click rate function
// Add a version check
//

function UltimateCookie() {
	this.AUTO_CLICK_DELAY = 1;
	this.AUTO_BUY_DELAY = 50;
	this.DEBUG_VERIFY = true;

	this.enable();
}

UltimateCookie.prototype.enable = function() {
	this.autoClicker = setInterval(Game.ClickCookie, this.AUTO_CLICK_DELAY);
	this.autoBuyer = setInterval(AutoBuy, this.AUTO_BUY_DELAY);
}

UltimateCookie.prototype.disable = function() {
	clearInterval(this.autoClicker);
	clearInterval(this.autoBuyer);
}

UltimateCookie.prototype.timeToBuy = function(cps, a, b) {
	return a.getCost() / cps + b.getCost() / (cps + a.getCps());
}

UltimateCookie.prototype.createPurchaseList = function() {
	var purchases = new Array();

	// Add the buildings
	var i;
	for (i = 0; i < Game.ObjectsById.length; ++i) {
		purchases.push(new PurchasableBuilding(Game.ObjectsById[i]));
	}

	// Add the upgrades
	for (i = 0; i < Game.UpgradesInStore.length; ++i) {
		purchases.push(new PurchasableUpgrade(Game.UpgradesInStore[i]));
	}

	return purchases;
}

UltimateCookie.prototype.determineNextPurchase = function() {

	var purchases = this.createPurchaseList();
	var next = purchases[0];
	var cps = this.effectiveCps();

	var i;
	for (i = 1; i < purchases.length; ++i) {
		if (this.timeToBuy(cps, next, purchases[i]) > this.timeToBuy(cps, purchases[i], next)) {
			next = purchases[i];
		}
	}

	if (this.lastDeterminedPurchase == undefined) {
		this.lastDeterminedPurchase == "";
	}

	if (next.toString() != this.lastDeterminedPurchase) {
		this.lastDeterminedPurchase = next.toString();
		console.log("Next purchase: " + this.lastDeterminedPurchase);
		if (this.DEBUG_VERIFY) {
			var e = new Evaluator();
			e.syncToGame();
			if (e.getCps() != Game.cookiesPs) {
				console.log("Evaluator Error - Predicted Cps: " + e.getCps() + ", Actual Cps: " + Game.cookiesPs);
				ultimateCookie.disable();
			}
		}
	}

	return next;
}

UltimateCookie.prototype.autoBuy = function() {
	var nextPurchase = this.determineNextPurchase();

	if (Game.cookies > nextPurchase.getCost()) {
		nextPurchase.purchase();
	}
}

UltimateCookie.prototype.effectiveCps = function() {
	// Assume 250 clicks per second
	return Game.cookiesPs + this.clickRate() * Game.mouseCps();
}

UltimateCookie.prototype.clickRate = function() {
	// Assume 250 clicks per second for now
	return 250;
}

function EvaluatorBuilding(baseCost, baseCps, name) {
	this.baseCost = baseCost;
	this.baseCps = baseCps;
	this.name = name;
	this.quantity = 0;
}

EvaluatorBuilding.prototype.getCps = function() {
	return this.quantity * this.baseCps;
}

EvaluatorBuilding.prototype.getCost = function() {
	return this.baseCost * Math.pow(1.15, this.quantity);
}

function Evaluator() {
	this.buildings = new Array();
	this.buildings.push(new EvaluatorBuilding(         15,        0.1, "Cursor"));
	this.buildings.push(new EvaluatorBuilding(        100,        0.5, "Grandma"));
	this.buildings.push(new EvaluatorBuilding(        500,        4.0, "Farm"));
	this.buildings.push(new EvaluatorBuilding(       3000,       10.0, "Factory"));
	this.buildings.push(new EvaluatorBuilding(      10000,       40.0, "Mine"));
	this.buildings.push(new EvaluatorBuilding(      40000,      100.0, "Shipment"));
	this.buildings.push(new EvaluatorBuilding(     200000,      400.0, "Alchemy lab"));
	this.buildings.push(new EvaluatorBuilding(    1666666,      666.0, "Portal"));
	this.buildings.push(new EvaluatorBuilding(  123456789,    98765.0, "Time Machine"));
	this.buildings.push(new EvaluatorBuilding( 3999999999,   999999.0, "Antimatter condenser"));
	this.buildings.push(new EvaluatorBuilding(75000000000, 10000000.0, "Prism"));
}

//
// Calculate the total Cps generated by the game in this state
//
Evaluator.prototype.getCps = function() {
	var i;
	var cps = 0;
	for (i = 0; i < this.buildings.length; ++i) {
		cps += this.buildings[i].getCps();
	}
	return cps;
}

//
// Sync an evaluator with the current in game store
//
Evaluator.prototype.syncToGame = function() {
	var i;
	for (i = 0; i < Game.ObjectsById.length && i < this.buildings.length; ++i) {
		this.buildings[i].quantity = Game.ObjectsById[i].amount;
	}
}

//
// Class to represent buildings for cost and buy order evaluation
//

function PurchasableBuilding(building) {
	this.building = building;
}

PurchasableBuilding.prototype.toString = function() {
	return "Building: " + this.building.displayName + " " + (this.building.amount + 1);
}

PurchasableBuilding.prototype.getCost = function() {
	return this.building.getPrice();
}

PurchasableBuilding.prototype.getCps = function() {
	return this.building.cps();
}

PurchasableBuilding.prototype.purchase = function() {
	this.building.buy(1);
}

//
// Class to represent upgrades for cost and buy order evaluation
//

function BaseCpsUpgrade(index, base, amount) {
	this.index = index;
	this.base = base;
	this.amount = amount;
	this.getCps = function() {
		return Game.ObjectsById[this.index].storedTotalCps * this.amount / this.base;
	}
}

// Upgrades that double the CPS of a building type
function DoublerUpgrade(index) {
	this.index = index;
	this.getCps = function() {
		return Game.ObjectsById[this.index].storedTotalCps;
	}
}

// Upgrades that double the CPS of clicking
function ClickDoublerUpgrade() {
	this.getCps = function() {
		return Game.mouseCps() * ultimateCookie.clickRate();
	}
}

// Upgrades that combine the effects of two or more other upgrade types
function ComboUpgrade(upgrades) {
	this.upgrades = upgrades;
	this.getCps = function() {
		var i;
		var cps = 0;
		for (i = 0; i < this.upgrades.length; ++i) {
			cps = cps + this.upgrades[i].getCps();
		}
		return cps;
	}
}

// Unhandled upgrade type, set to 0 cps so basically never bought automatically
function UnknownUpgrade(name) {
	console.log("Unknown Upgrade: " + name);
	this.getCps = function() {
		return 0;
	}
}

function UpgradeInfo() {
	// Index into the Game.ObjectsByID array
	this.CURSOR_INDEX = 0;
	this.GRANDMA_INDEX = 1;
	this.FARM_INDEX = 2;
	this.FACTORY_INDEX = 3;

	this.buildingMultipliers = new Array(Game.ObjectsById.length);

	// Base CPS upgrades are those that adjust the base CPS of a building
//	this.baseCpsUpgrades = new Array();
//	this.baseCpsUpgrades.push([this.GRANDMA_INDEX, 0.3, "Forwards from grandma"]);
//	this.baseCpsUpgrades.push([this.FARM_INDEX, 1.0, ]);
//	this.baseCpsUpgrades.push([this.FACTORY_INDEX, 4.0, "Sturdier conveyor belts"]);

	// Create the array of known Upgrade functions
	this.upgradeFunctions = {};

	// Base CpS upgrades increase the base cps of a building
	this.upgradeFunctions["Cheap hoes"] = new BaseCpsUpgrade(this.FARM_INDEX, 4, 1);

	// Doubler Upgrades are those that double the productivity of a type of building
	this.upgradeFunctions["Steel-plated rolling pins"] = new DoublerUpgrade(this.GRANDMA_INDEX);
	this.upgradeFunctions["Lubricated dentures"] = new DoublerUpgrade(this.GRANDMA_INDEX);
	this.upgradeFunctions["Fertilizer"] = new DoublerUpgrade(this.FARM_INDEX);

	// Combo upgrades, combine a couple of effects
//	this.upgradeFunctions["Reinforced Index Finger"] = new ComboUpgrade([
//		new BaseUpgrade(this.CURSOR_INDEX, 0.4, 0.1),
//		new ClickBaseUpgrade(1)
//	]);
	this.upgradeFunctions["Carpal tunnel prevention cream"] = new ComboUpgrade([
		new DoublerUpgrade(this.CURSOR_INDEX),
		new ClickDoublerUpgrade()
	]);
	this.upgradeFunctions["Ambidextrous"] = new ComboUpgrade([
		new DoublerUpgrade(this.CURSOR_INDEX),
		new ClickDoublerUpgrade()
	]);
}

UpgradeInfo.prototype.getUpgradeCpsFunction = function(upgrade) {
	if (this.upgradeFunctions[upgrade.name] == undefined) {
		this.upgradeFunctions[upgrade.name] = new UnknownUpgrade(upgrade.name);
	}
	return this.upgradeFunctions[upgrade.name];
}

UpgradeInfo.prototype.getScale = function(buildingIndex) {
	var s = 1;
	var i;
	for (i = 0; i < this.doublerUpgrades.length; ++i) {
		if (doublerUpgrades[i][0] == buildingIndex && Game.has(doublerUpgrades[i][1])) {
			s = s * 2;
		}
	}
	return s;
}

//
// Class to represent an individual purchasable upgrade
//

function PurchasableUpgrade(upgrade) {
	this.upgrade = upgrade;
	this.upgradeFunction = upgradeInfo.getUpgradeCpsFunction(upgrade);
}

PurchasableUpgrade.prototype.toString = function() {
	return "Upgrade: " + this.upgrade.name;
}

PurchasableUpgrade.prototype.getCost = function() {
	return this.upgrade.getPrice();
}

PurchasableUpgrade.prototype.purchase = function() {
	this.upgrade.buy(0);
}

PurchasableUpgrade.prototype.getCps = function() {
	return this.upgradeFunction.getCps();
}

var upgradeInfo = new UpgradeInfo();
var ultimateCookie = new UltimateCookie();

function AutoBuy() { ultimateCookie.autoBuy(); }
